apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: omeka-classic
spec:
  ports:
    - port: 3306
  selector:
    app: omeka-classic
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlomeka-pv
  labels:
    app: omeka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: omekac-mysql
  labels:
    app: omeka-classic
spec:
  selector:
    matchLabels:
      app: omeka-classic
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: omeka-classic
        tier: mysql
      annotations:
        backup.velero.io/backup-volumes: omysql-persistent-storage
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: omeka
        - name: MYSQL_USER
          value: 
        - name: MYSQL_PASSWORD
          value: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-passww
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: omysql-persistent-storage
          mountPath: /var/lib/mysql
        securityContext:
          privileged: true
      volumes:
      - name: omysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysqlomeka-pv
        # mysql-data:
        #   driver: local
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: omeka-mysql
#   labels:
#     group: db
# data:
#   MYSQL_ROOT_PASSWORD: omeka
#   MYSQL_DATABASE: omeka
#   MYSQL_USER: omeka
#   MYSQL_PASSWORD: omeka
